DROP TABLE RESULTADO_MEGASENA;
CREATE TABLE RESULTADO_MEGASENA
(
	NUM_CONCURSO VARCHAR(50),
	DAT_CONCURSO VARCHAR(11),
	NUM_SORTEADOS VARCHAR(50),
	QTD_GANHADORES_SENA VARCHAR(50),
	VALOR_GANHADORES_SENA VARCHAR(50),
	QTD_GANHADORES_QUINA VARCHAR(50),
	VALOR_GANHADORES_QUINA VARCHAR(50),
	QTD_GANHADORES_QUADRA VARCHAR(50),
	VALOR_GANHADORES_QUADRA VARCHAR(50),
	VALOR_ACUMULADO VARCHAR(50)
);
GO
DROP TABLE RESULTADO_LOTOMANIA;
CREATE TABLE RESULTADO_LOTOMANIA
(
	NUM_CONCURSO VARCHAR(50),
	DAT_CONCURSO VARCHAR(11),
	NUM_SORTEADOS VARCHAR(100),
	QTD_GANHADORES_20PTS VARCHAR(50),
	VALOR_GANHADORES_20PTS VARCHAR(50),
	QTD_GANHADORES_19PTS VARCHAR(50),
	VALOR_GANHADORES_19PTS VARCHAR(50),
	QTD_GANHADORES_18PTS VARCHAR(50),
	VALOR_GANHADORES_18PTS VARCHAR(50),
	QTD_GANHADORES_17PTS VARCHAR(50),
	VALOR_GANHADORES_17PTS VARCHAR(50),
	QTD_GANHADORES_16PTS VARCHAR(50),
	VALOR_GANHADORES_16PTS VARCHAR(50),
	QTD_GANHADORES_15PTS VARCHAR(50),
	VALOR_GANHADORES_15PTS VARCHAR(50),
	QTD_GANHADORES_0PTS VARCHAR(50),
	VALOR_GANHADORES_0PTS VARCHAR(50),
	VALOR_ACUMULADO VARCHAR(50)
);
GO
DROP TABLE RESULTADO_LOTOFACIL;
CREATE TABLE RESULTADO_LOTOFACIL
(
	NUM_CONCURSO_1 VARCHAR(50),
	DAT_CONCURSO_1 VARCHAR(11),
	NUM_SORTEADOS_1 VARCHAR(100),
	QTD_GANHADORES_1_15PTS VARCHAR(50),
	VALOR_GANHADORES_1_15PTS VARCHAR(50),
	QTD_GANHADORES_1_14PTS VARCHAR(50),
	VALOR_GANHADORES_1_14PTS VARCHAR(50),
	QTD_GANHADORES_1_13PTS VARCHAR(50),
	VALOR_GANHADORES_1_13PTS VARCHAR(50),
	QTD_GANHADORES_1_12PTS VARCHAR(50),
	VALOR_GANHADORES_1_12PTS VARCHAR(50),
	QTD_GANHADORES_1_11PTS VARCHAR(50),
	VALOR_GANHADORES_1_11PTS VARCHAR(50),
	VALOR_ACUMULADO_1 VARCHAR(50),
	NUM_CONCURSO_2 VARCHAR(50),
	DAT_CONCURSO_2 VARCHAR(11),
	NUM_SORTEADOS_2 VARCHAR(100),
	QTD_GANHADORES_2_15PTS VARCHAR(50),
	VALOR_GANHADORES_2_15PTS VARCHAR(50),
	QTD_GANHADORES_2_14PTS VARCHAR(50),
	VALOR_GANHADORES_2_14PTS VARCHAR(50),
	QTD_GANHADORES_2_13PTS VARCHAR(50),
	VALOR_GANHADORES_2_13PTS VARCHAR(50),
	QTD_GANHADORES_2_12PTS VARCHAR(50),
	VALOR_GANHADORES_2_12PTS VARCHAR(50),
	QTD_GANHADORES_2_11PTS VARCHAR(50),
	VALOR_GANHADORES_2_11PTS VARCHAR(50),
	VALOR_ACUMULADO_2 VARCHAR(50)
);
GO
DROP TABLE RESULTADO_QUINA;
CREATE TABLE RESULTADO_QUINA
(
	NUM_CONCURSO_1 VARCHAR(50),
	DAT_CONCURSO_1 VARCHAR(11),
	NUM_SORTEADOS_1 VARCHAR(30),
	QTD_GANHADORES_QUINA_1 VARCHAR(50),
	VALOR_GANHADORES_QUINA_1 VARCHAR(50),
	QTD_GANHADORES_QUADRA_1 VARCHAR(50),
	VALOR_GANHADORES_QUADRA_1 VARCHAR(50),
	QTD_GANHADORES_TERNO_1 VARCHAR(50),
	VALOR_GANHADORES_TERNO_1 VARCHAR(50),
	QTD_GANHADORES_DUQUE_1 VARCHAR(50),
	VALOR_GANHADORES_DUQUE_1 VARCHAR(50),
	VALOR_ACUMULADO_1 VARCHAR(50),
	NUM_CONCURSO_2 VARCHAR(50),
	DAT_CONCURSO_2 VARCHAR(11),
	NUM_SORTEADOS_2 VARCHAR(30),
	QTD_GANHADORES_QUINA_2 VARCHAR(50),
	VALOR_GANHADORES_QUINA_2 VARCHAR(50),
	QTD_GANHADORES_QUADRA_2 VARCHAR(50),
	VALOR_GANHADORES_QUADRA_2 VARCHAR(50),
	QTD_GANHADORES_TERNO_2 VARCHAR(50),
	VALOR_GANHADORES_TERNO_2 VARCHAR(50),
	QTD_GANHADORES_DUQUE_2 VARCHAR(50),
	VALOR_GANHADORES_DUQUE_2 VARCHAR(50),
	VALOR_ACUMULADO_2 VARCHAR(50)
);
GO
DROP TABLE RESULTADO_JOGOS_LOTECA;
DROP TABLE RESULTADO_LOTECA;
CREATE TABLE RESULTADO_LOTECA
(
	NUM_CONCURSO varchar(50), 
	DAT_CONCURSO varchar(11) ,
	QTD_GANHADORES_15PTS varchar(50) ,
	VALOR_GANHADORES_15PTS varchar(50), 
	QTD_GANHADORES_16PTS varchar(50) ,
	VALOR_GANHADORES_16PTS varchar(50), 
	VALOR_ACUMULADO varchar(50)
);
CREATE TABLE RESULTADO_JOGOS_LOTECA
(
	NUM_CONCURSO VARCHAR(50),
	IND_FAIXA INT,
	IND_TIPO_RESULTADO INT,
    CONSTRAINT FK_LOTECA_JOGOS_LOTECA
    FOREIGN KEY (NUM_CONCURSO)
    REFERENCES RESULTADO_LOTECA (NUM_CONCURSO)
);
GO