TRUNCATE TABLE RESULTADO_MEGASENA;
TRUNCATE TABLE RESULTADO_LOTOMANIA;
TRUNCATE TABLE RESULTADO_LOTOFACIL;
TRUNCATE TABLE RESULTADO_QUINA;
TRUNCATE TABLE RESULTADO_JOGOS_LOTECA;
TRUNCATE TABLE RESULTADO_LOTECA;
TRUNCATE TABLE RESULTADO_LOTECA;
TRUNCATE TABLE RESULTADO_TIMEMANIA;
COMMIT;
DROP TABLE RESULTADO_MEGASENA;
CREATE TABLE RESULTADO_MEGASENA
(
	NUM_CONCURSO VARCHAR(50),
	DAT_CONCURSO VARCHAR(11),
	NUM_SORTEADOS VARCHAR(50),
	QTD_GANHADORES_SENA VARCHAR(50),
	VALOR_GANHADORES_SENA VARCHAR(50),
	QTD_GANHADORES_QUINA VARCHAR(50),
	VALOR_GANHADORES_QUINA VARCHAR(50),
	QTD_GANHADORES_QUADRA VARCHAR(50),
	VALOR_GANHADORES_QUADRA VARCHAR(50),
	VALOR_ACUMULADO VARCHAR(50)
);
GO
DROP TABLE RESULTADO_LOTOMANIA;
CREATE TABLE RESULTADO_LOTOMANIA
(
	NUM_CONCURSO VARCHAR(50),
	DAT_CONCURSO VARCHAR(11),
	NUM_SORTEADOS VARCHAR(100),
	QTD_GANHADORES_20PTS VARCHAR(50),
	VALOR_GANHADORES_20PTS VARCHAR(50),
	QTD_GANHADORES_19PTS VARCHAR(50),
	VALOR_GANHADORES_19PTS VARCHAR(50),
	QTD_GANHADORES_18PTS VARCHAR(50),
	VALOR_GANHADORES_18PTS VARCHAR(50),
	QTD_GANHADORES_17PTS VARCHAR(50),
	VALOR_GANHADORES_17PTS VARCHAR(50),
	QTD_GANHADORES_16PTS VARCHAR(50),
	VALOR_GANHADORES_16PTS VARCHAR(50),
	QTD_GANHADORES_15PTS VARCHAR(50),
	VALOR_GANHADORES_15PTS VARCHAR(50),
	QTD_GANHADORES_0PTS VARCHAR(50),
	VALOR_GANHADORES_0PTS VARCHAR(50),
	VALOR_ACUMULADO VARCHAR(50)
);
GO
DROP TABLE RESULTADO_LOTOFACIL;
CREATE TABLE RESULTADO_LOTOFACIL
(
	NUM_CONCURSO_1 VARCHAR(50),
	DAT_CONCURSO_1 VARCHAR(11),
	NUM_SORTEADOS_1 VARCHAR(100),
	QTD_GANHADORES_1_15PTS VARCHAR(50),
	VALOR_GANHADORES_1_15PTS VARCHAR(50),
	QTD_GANHADORES_1_14PTS VARCHAR(50),
	VALOR_GANHADORES_1_14PTS VARCHAR(50),
	QTD_GANHADORES_1_13PTS VARCHAR(50),
	VALOR_GANHADORES_1_13PTS VARCHAR(50),
	QTD_GANHADORES_1_12PTS VARCHAR(50),
	VALOR_GANHADORES_1_12PTS VARCHAR(50),
	QTD_GANHADORES_1_11PTS VARCHAR(50),
	VALOR_GANHADORES_1_11PTS VARCHAR(50),
	VALOR_ACUMULADO_1 VARCHAR(50),
	NUM_CONCURSO_2 VARCHAR(50),
	DAT_CONCURSO_2 VARCHAR(11),
	NUM_SORTEADOS_2 VARCHAR(100),
	QTD_GANHADORES_2_15PTS VARCHAR(50),
	VALOR_GANHADORES_2_15PTS VARCHAR(50),
	QTD_GANHADORES_2_14PTS VARCHAR(50),
	VALOR_GANHADORES_2_14PTS VARCHAR(50),
	QTD_GANHADORES_2_13PTS VARCHAR(50),
	VALOR_GANHADORES_2_13PTS VARCHAR(50),
	QTD_GANHADORES_2_12PTS VARCHAR(50),
	VALOR_GANHADORES_2_12PTS VARCHAR(50),
	QTD_GANHADORES_2_11PTS VARCHAR(50),
	VALOR_GANHADORES_2_11PTS VARCHAR(50),
	VALOR_ACUMULADO_2 VARCHAR(50)
);
GO
DROP TABLE RESULTADO_QUINA;
CREATE TABLE RESULTADO_QUINA
(
	NUM_CONCURSO_1 VARCHAR(50),
	DAT_CONCURSO_1 VARCHAR(11),
	NUM_SORTEADOS_1 VARCHAR(30),
	QTD_GANHADORES_QUINA_1 VARCHAR(50),
	VALOR_GANHADORES_QUINA_1 VARCHAR(50),
	QTD_GANHADORES_QUADRA_1 VARCHAR(50),
	VALOR_GANHADORES_QUADRA_1 VARCHAR(50),
	QTD_GANHADORES_TERNO_1 VARCHAR(50),
	VALOR_GANHADORES_TERNO_1 VARCHAR(50),
	QTD_GANHADORES_DUQUE_1 VARCHAR(50),
	VALOR_GANHADORES_DUQUE_1 VARCHAR(50),
	VALOR_ACUMULADO_1 VARCHAR(50),
	NUM_CONCURSO_2 VARCHAR(50),
	DAT_CONCURSO_2 VARCHAR(11),
	NUM_SORTEADOS_2 VARCHAR(30),
	QTD_GANHADORES_QUINA_2 VARCHAR(50),
	VALOR_GANHADORES_QUINA_2 VARCHAR(50),
	QTD_GANHADORES_QUADRA_2 VARCHAR(50),
	VALOR_GANHADORES_QUADRA_2 VARCHAR(50),
	QTD_GANHADORES_TERNO_2 VARCHAR(50),
	VALOR_GANHADORES_TERNO_2 VARCHAR(50),
	QTD_GANHADORES_DUQUE_2 VARCHAR(50),
	VALOR_GANHADORES_DUQUE_2 VARCHAR(50),
	VALOR_ACUMULADO_2 VARCHAR(50)
);
GO
DROP TABLE RESULTADO_JOGOS_LOTECA;
DROP TABLE RESULTADO_LOTECA;
CREATE TABLE RESULTADO_LOTECA
(
	NUM_CONCURSO varchar(50), 
	DAT_CONCURSO varchar(11) ,
	QTD_GANHADORES_15PTS varchar(50) ,
	VALOR_GANHADORES_15PTS varchar(50), 
	QTD_GANHADORES_16PTS varchar(50) ,
	VALOR_GANHADORES_16PTS varchar(50), 
	VALOR_ACUMULADO varchar(50)
);
CREATE TABLE RESULTADO_JOGOS_LOTECA
(
	NUM_CONCURSO VARCHAR(50),
	IND_FAIXA INT,
	IND_TIPO_RESULTADO INT,
    CONSTRAINT FK_LOTECA_JOGOS_LOTECA
    FOREIGN KEY (NUM_CONCURSO)
    REFERENCES RESULTADO_LOTECA (NUM_CONCURSO)
);
GO
DROP TABLE RESULTADO_TIMEMANIA;
CREATE TABLE RESULTADO_TIMEMANIA
(
	NUM_CONCURSO VARCHAR(50),
	DAT_CONCURSO VARCHAR(11),
	NUM_SORTEADOS VARCHAR(100),
	QTD_GANHADORES_7PTS VARCHAR(50),
	VALOR_GANHADORES_7PTS VARCHAR(50),
	QTD_GANHADORES_6PTS VARCHAR(50),
	VALOR_GANHADORES_6PTS VARCHAR(50),
	QTD_GANHADORES_5PTS VARCHAR(50),
	VALOR_GANHADORES_5PTS VARCHAR(50),
	QTD_GANHADORES_4PTS VARCHAR(50),
	VALOR_GANHADORES_4PTS VARCHAR(50),
	QTD_GANHADORES_3PTS VARCHAR(50),
	VALOR_GANHADORES_3PTS VARCHAR(50),
	QTD_GANHADORES_TIME_CORACAO VARCHAR(50),
	VALOR_GANHADORES_TIME_CORACAO VARCHAR(50),
	DSC_TIME_SORTEADO VARCHAR(50),
	VALOR_ACUMULADO VARCHAR(50)
);
GO
DROP TABLE RESULTADO_SUPERSETE;
CREATE TABLE RESULTADO_SUPERSETE
(
	NUM_CONCURSO VARCHAR(50),
	DAT_CONCURSO VARCHAR(11),
	NUM_SORTEADOS VARCHAR(100),
	QTD_GANHADORES_7PTS VARCHAR(50),
	VALOR_GANHADORES_7PTS VARCHAR(50),
	QTD_GANHADORES_6PTS VARCHAR(50),
	VALOR_GANHADORES_6PTS VARCHAR(50),
	QTD_GANHADORES_5PTS VARCHAR(50),
	VALOR_GANHADORES_5PTS VARCHAR(50),
	QTD_GANHADORES_4PTS VARCHAR(50),
	VALOR_GANHADORES_4PTS VARCHAR(50),
	QTD_GANHADORES_3PTS VARCHAR(50),
	VALOR_GANHADORES_3PTS VARCHAR(50),
	VALOR_ACUMULADO VARCHAR(50)
);
========================================================================================================================================================================
script inicial para SUPER SETE
insert into RESULTADO_SUPERSETE values('1','02/10/2020','2-9-9-8-7-7-6','0','0','12','16.916,44','272','1.066,16','4.330','66,97','41.129','5,00','744.334,69');
========================================================================================================================================================================
GO
DROP TABLE RESULTADO_DIADESORTE;
CREATE TABLE RESULTADO_DIADESORTE
(
	NUM_CONCURSO VARCHAR(50),
	DAT_CONCURSO VARCHAR(11),
	NUM_SORTEADOS VARCHAR(100),
	QTD_GANHADORES_7PTS VARCHAR(50),
	VALOR_GANHADORES_7PTS VARCHAR(50),
	QTD_GANHADORES_6PTS VARCHAR(50),
	VALOR_GANHADORES_6PTS VARCHAR(50),
	QTD_GANHADORES_5PTS VARCHAR(50),
	VALOR_GANHADORES_5PTS VARCHAR(50),
	QTD_GANHADORES_4PTS VARCHAR(50),
	VALOR_GANHADORES_4PTS VARCHAR(50),
	NUM_MES_SORTEADO VARCHAR(50),
	NUM_GANHADORES VARCHAR(50),
	VALOR_TOTAL VARCHAR(50),
	VALOR_ACUMULADO VARCHAR(50)
);
GO
DROP TABLE USUARIO;
CREATE TABLE USUARIO
(
	COD_USUARIO INT PRIMARY KEY AUTO_INCREMENT ,
	DSC_LOGIN VARCHAR(30),
	DSC_SENHA VARCHAR(30),
	IND_ADMINISTRADOR BIT
);

insert into USUARIO (DSC_LOGIN,DSC_SENHA,IND_ADMINISTRADOR) VALUES('admin','uldiario09092020',1);
insert into USUARIO (DSC_LOGIN,DSC_SENHA,IND_ADMINISTRADOR) VALUES('usuario','uldiario09092020',0);
commit;