DROP TABLE RESULTADO_MEGASENA;
CREATE TABLE RESULTADO_MEGASENA
(
	NUM_CONCURSO INT,
	DAT_CONCURSO VARCHAR(11),
	NUM_SORTEADOS VARCHAR(30),
	QTD_GANHADORES_SENA INT,
	VALOR_GANHADORES_SENA DECIMAL(18,2),
	QTD_GANHADORES_QUINA INT,
	VALOR_GANHADORES_QUINA DECIMAL(18,2),
	QTD_GANHADORES_QUADRA INT,
	VALOR_GANHADORES_QUADRA DECIMAL(18,2),
	VALOR_ACUMULADO DECIMAL(18,2)
);
GO
DROP TABLE RESULTADO_LOTOMANIA;
CREATE TABLE RESULTADO_LOTOMANIA
(
	NUM_CONCURSO INT,
	DAT_CONCURSO VARCHAR(11),
	NUM_SORTEADOS VARCHAR(100),
	QTD_GANHADORES_20PTS INT,
	VALOR_GANHADORES_20PTS DECIMAL(18,2),
	QTD_GANHADORES_19PTS INT,
	VALOR_GANHADORES_19PTS DECIMAL(18,2),
	QTD_GANHADORES_18PTS INT,
	VALOR_GANHADORES_18PTS DECIMAL(18,2),
	QTD_GANHADORES_17PTS INT,
	VALOR_GANHADORES_17PTS DECIMAL(18,2),
	QTD_GANHADORES_16PTS INT,
	VALOR_GANHADORES_16PTS DECIMAL(18,2),
	QTD_GANHADORES_15PTS INT,
	VALOR_GANHADORES_15PTS DECIMAL(18,2),
	QTD_GANHADORES_0PTS INT,
	VALOR_GANHADORES_0PTS DECIMAL(18,2),
	VALOR_ACUMULADO DECIMAL(18,2)
);
GO
DROP TABLE RESULTADO_LOTOFACIL;
CREATE TABLE RESULTADO_LOTOFACIL
(
	NUM_CONCURSO_1 INT,
	DAT_CONCURSO_1 VARCHAR(11),
	NUM_SORTEADOS_1 VARCHAR(30),
	QTD_GANHADORES_1_15PTS INT,
	VALOR_GANHADORES_1_15PTS DECIMAL(18,2),
	QTD_GANHADORES_1_14PTS INT,
	VALOR_GANHADORES_1_14PTS DECIMAL(18,2),
	QTD_GANHADORES_1_13PTS INT,
	VALOR_GANHADORES_1_13PTS DECIMAL(18,2),
	QTD_GANHADORES_1_12PTS INT,
	VALOR_GANHADORES_1_12PTS DECIMAL(18,2),
	QTD_GANHADORES_1_11PTS INT,
	VALOR_GANHADORES_1_11PTS DECIMAL(18,2),
	VALOR_ACUMULADO_1 DECIMAL(18,2),
	NUM_CONCURSO_2 INT,
	DAT_CONCURSO_2 DATE,
	NUM_SORTEADOS_2 VARCHAR(30),
	QTD_GANHADORES_2_15PTS INT,
	VALOR_GANHADORES_2_15PTS DECIMAL(18,2),
	QTD_GANHADORES_2_14PTS INT,
	VALOR_GANHADORES_2_14PTS DECIMAL(18,2),
	QTD_GANHADORES_2_13PTS INT,
	VALOR_GANHADORES_2_13PTS DECIMAL(18,2),
	QTD_GANHADORES_2_12PTS INT,
	VALOR_GANHADORES_2_12PTS DECIMAL(18,2),
	QTD_GANHADORES_2_11PTS INT,
	VALOR_GANHADORES_2_11PTS DECIMAL(18,2),
	VALOR_ACUMULADO_2 DECIMAL(18,2)
);
GO
DROP TABLE RESULTADO_QUINA;
CREATE TABLE RESULTADO_QUINA
(
	NUM_CONCURSO_1 INT,
	DAT_CONCURSO_1 VARCHAR(11),
	NUM_SORTEADOS_1 VARCHAR(30),
	QTD_GANHADORES_QUINA_1 INT,
	VALOR_GANHADORES_QUINA_1 DECIMAL(18,2),
	QTD_GANHADORES_QUADRA_1 INT,
	VALOR_GANHADORES_QUADRA_1 DECIMAL(18,2),
	QTD_GANHADORES_TERNO_1 INT,
	VALOR_GANHADORES_TERNO_1 DECIMAL(18,2),
	QTD_GANHADORES_DUQUE_1 INT,
	VALOR_GANHADORES_DUQUE_1 DECIMAL(18,2),
	VALOR_ACUMULADO_1 DECIMAL(18,2),
	NUM_CONCURSO_2 INT,
	DAT_CONCURSO_2 DATE,
	NUM_SORTEADOS_2 VARCHAR(30),
	QTD_GANHADORES_QUINA_2 INT,
	VALOR_GANHADORES_QUINA_2 DECIMAL(18,2),
	QTD_GANHADORES_QUADRA_2 INT,
	VALOR_GANHADORES_QUADRA_2 DECIMAL(18,2),
	QTD_GANHADORES_TERNO_2 INT,
	VALOR_GANHADORES_TERNO_2 DECIMAL(18,2),
	QTD_GANHADORES_DUQUE_2 INT,
	VALOR_GANHADORES_DUQUE_2 DECIMAL(18,2),
	VALOR_ACUMULADO_2 DECIMAL(18,2)
);
GO